
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author david
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    ArrayList<Pc> list = new ArrayList();
    int cont = 0;

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JF_CRUD = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt_ip = new javax.swing.JTextField();
        jt_mask = new javax.swing.JTextField();
        jt_host = new javax.swing.JTextField();
        jr_lap = new javax.swing.JRadioButton();
        jr_desk = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jb_siguiente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_listar = new javax.swing.JTextArea();
        jbListar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JbEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_eliminar = new javax.swing.JTextArea();
        jtelim = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JF_Lap = new javax.swing.JFrame();
        jt_marca = new javax.swing.JTextField();
        jt_pantalla = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jb_Agregarlap = new javax.swing.JButton();
        jrl_si = new javax.swing.JRadioButton();
        jrl_no = new javax.swing.JRadioButton();
        JF_Desk = new javax.swing.JFrame();
        jt_ram = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jt_alma = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jt_tipohard = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jrd_si = new javax.swing.JRadioButton();
        jrd_no = new javax.swing.JRadioButton();
        JB_Agregardesk = new javax.swing.JButton();
        bg_tipopc = new javax.swing.ButtonGroup();
        bg_Grafica = new javax.swing.ButtonGroup();
        bg_rgb = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JB_CRUD = new javax.swing.JButton();
        JB_Simular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        JF_CRUD.setResizable(false);
        JF_CRUD.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        jLabel3.setText("IP:");

        jLabel4.setText("Mask:");

        jLabel5.setText("Hostname:");

        bg_tipopc.add(jr_lap);
        jr_lap.setText("Laptop");

        bg_tipopc.add(jr_desk);
        jr_desk.setText("Escritorio");

        jLabel6.setText("Tipo");

        jb_siguiente.setText("Siguiente");
        jb_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_siguienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jr_lap, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jr_desk, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt_ip)
                                .addComponent(jt_mask)
                                .addComponent(jt_host, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jb_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_mask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jt_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jr_lap)
                    .addComponent(jr_desk)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addComponent(jb_siguiente)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel2);

        jt_listar.setColumns(20);
        jt_listar.setRows(5);
        jScrollPane1.setViewportView(jt_listar);

        jbListar.setText("Listar");
        jbListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbListarMouseClicked(evt);
            }
        });
        jbListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbListar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbListar)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel3);

        JbEliminar.setText("Eliminar");
        JbEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JbEliminarMouseClicked(evt);
            }
        });

        jt_eliminar.setColumns(20);
        jt_eliminar.setRows(5);
        jScrollPane2.setViewportView(jt_eliminar);

        jLabel14.setText("Opcion a eliminar:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(331, 331, 331)
                                .addComponent(JbEliminar)))
                        .addGap(0, 370, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtelim)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jtelim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(JbEliminar)
                .addGap(165, 165, 165))
        );

        jTabbedPane1.addTab("Eliminar", jPanel4);

        JF_CRUD.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        JF_Lap.setResizable(false);

        jLabel7.setText("Marca:");

        jLabel8.setText("Pantalla:");

        jLabel9.setText("RGB:");

        jb_Agregarlap.setText("Agregar");
        jb_Agregarlap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AgregarlapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_AgregarlapMouseEntered(evt);
            }
        });

        bg_rgb.add(jrl_si);
        jrl_si.setText("Si");

        bg_Grafica.add(jrl_no);
        jrl_no.setText("No");

        javax.swing.GroupLayout JF_LapLayout = new javax.swing.GroupLayout(JF_Lap.getContentPane());
        JF_Lap.getContentPane().setLayout(JF_LapLayout);
        JF_LapLayout.setHorizontalGroup(
            JF_LapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_LapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JF_LapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JF_LapLayout.createSequentialGroup()
                        .addGroup(JF_LapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JF_LapLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JF_LapLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JF_LapLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(JF_LapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_Agregarlap)
                            .addGroup(JF_LapLayout.createSequentialGroup()
                                .addComponent(jrl_si, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrl_no, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(62, Short.MAX_VALUE))))
        );
        JF_LapLayout.setVerticalGroup(
            JF_LapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_LapLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(JF_LapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(JF_LapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(JF_LapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jrl_si)
                    .addComponent(jrl_no))
                .addGap(50, 50, 50)
                .addComponent(jb_Agregarlap)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        JF_Desk.setResizable(false);

        jLabel10.setText("Ram:");

        jLabel11.setText("Almacenamiento:");

        jLabel12.setText("Disco Duro:");

        jLabel13.setText("Grafica:");

        bg_Grafica.add(jrd_si);
        jrd_si.setText("Si");

        bg_Grafica.add(jrd_no);
        jrd_no.setText("No");

        JB_Agregardesk.setText("Agregar");
        JB_Agregardesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregardeskMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JF_DeskLayout = new javax.swing.GroupLayout(JF_Desk.getContentPane());
        JF_Desk.getContentPane().setLayout(JF_DeskLayout);
        JF_DeskLayout.setHorizontalGroup(
            JF_DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_DeskLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(JF_DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JF_DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JF_DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JF_DeskLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(JF_DeskLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JF_DeskLayout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)))
                    .addGroup(JF_DeskLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addGroup(JF_DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JB_Agregardesk, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jt_ram, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_alma)
                    .addComponent(jt_tipohard)
                    .addGroup(JF_DeskLayout.createSequentialGroup()
                        .addComponent(jrd_si, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrd_no, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        JF_DeskLayout.setVerticalGroup(
            JF_DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_DeskLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(JF_DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29)
                .addGroup(JF_DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jt_alma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(JF_DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jt_tipohard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(JF_DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jrd_si)
                    .addComponent(jrd_no))
                .addGap(26, 26, 26)
                .addComponent(JB_Agregardesk)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_CRUD.setBackground(new java.awt.Color(255, 140, 84));
        JB_CRUD.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        JB_CRUD.setForeground(new java.awt.Color(255, 255, 255));
        JB_CRUD.setText("CRUD");
        JB_CRUD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_CRUDMouseClicked(evt);
            }
        });
        JB_CRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CRUDActionPerformed(evt);
            }
        });
        jPanel1.add(JB_CRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 200, -1));

        JB_Simular.setBackground(new java.awt.Color(255, 140, 84));
        JB_Simular.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        JB_Simular.setForeground(new java.awt.Color(255, 255, 255));
        JB_Simular.setText("Simular");
        JB_Simular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_SimularMouseClicked(evt);
            }
        });
        jPanel1.add(JB_Simular, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Redes_neuronales_foto.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_CRUDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_CRUDMouseClicked
        // TODO add your handling code here:
        JF_CRUD.setLocationRelativeTo(null);
        JF_CRUD.setVisible(true);
        JF_CRUD.setSize(800, 500);
    }//GEN-LAST:event_JB_CRUDMouseClicked

    private void JB_SimularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_SimularMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_JB_SimularMouseClicked

    private void jb_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_siguienteMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < jt_ip.getText().length(); i++) {
            if (jt_ip.getText().charAt(i) == '.') {
                cont++;
            }
        }
        if (cont == 3) {
            if (jr_lap.isSelected()) {
                JF_Lap.setVisible(true);
                JF_Lap.setLocationRelativeTo(null);
                JF_Lap.setSize(214, 269);

            } else {
                JF_Desk.setVisible(true);
                JF_Desk.setLocationRelativeTo(null);
                JF_Desk.setSize(436, 329);
            }
        } else {
            JOptionPane.showMessageDialog(null, "IP no valida");
        }
    }//GEN-LAST:event_jb_siguienteMouseClicked

    private void jb_AgregarlapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarlapMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jb_AgregarlapMouseClicked

    private void JB_CRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CRUDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_CRUDActionPerformed

    private void jbListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbListarActionPerformed

    private void jbListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbListarMouseClicked
        // TODO add your handling code here:
        String listar = "";
        for (Pc pc : list) {
            listar+=list.indexOf(pc)+" "+pc.toStringp();
        }
        jt_listar.setText(listar);
    }//GEN-LAST:event_jbListarMouseClicked

    private void JbEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JbEliminarMouseClicked
        // TODO add your handling code here:
        int op
                = (int) Integer.parseInt(jtelim.getText());
        list.remove(op);
        JOptionPane.showMessageDialog(null, "Producto Eliminado exitosamente");


    }//GEN-LAST:event_JbEliminarMouseClicked

    private void jb_AgregarlapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarlapMouseEntered
        // Crear Laptop
        if (jrl_si.isSelected()) {
            list.add(new Laptop(jt_marca.getText(), jt_pantalla.getText(), true, jt_ip.getText(), jt_mask.getText(), jt_host.getText()));
            JF_Lap.setVisible(false);
        } else {
            list.add(new Laptop(jt_marca.getText(), jt_pantalla.getText(), false, jt_ip.getText(), jt_mask.getText(), jt_host.getText()));
            JF_Lap.setVisible(false);
        }
        jt_marca.setText("");
        jt_pantalla.setText("");
        jt_ip.setText("");
        jt_host.setText("");
        jt_mask.setText("");
        JOptionPane.showMessageDialog(null, "Agregado con exito");
    }//GEN-LAST:event_jb_AgregarlapMouseEntered

    private void JB_AgregardeskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregardeskMouseClicked
        // Crear Escritorio
        if (jrd_si.isSelected()) {
            list.add(new Escritorio((int) Integer.parseInt(jt_ram.getText()), (int) Integer.parseInt(jt_alma.getText()), jt_tipohard.getText(), true, jt_ip.getText(), jt_mask.getText(), jt_host.getText()));
            JF_Desk.setVisible(false);
        } else {
            list.add(new Escritorio((int) Integer.parseInt(jt_ram.getText()), (int) Integer.parseInt(jt_alma.getText()), jt_tipohard.getText(), false, jt_ip.getText(), jt_mask.getText(), jt_host.getText()));
            JF_Desk.setVisible(false);
        }
        jt_alma.setText("");
        jt_ram.setText("");
        jt_tipohard.setText("");
        jt_ip.setText("");
        jt_host.setText("");
        jt_mask.setText("");
        JOptionPane.showMessageDialog(null, "Agregado con exito");
    }//GEN-LAST:event_JB_AgregardeskMouseClicked

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        String listar = "";
        for (Pc object : list) {

            listar += "" + list.indexOf(object) + " " + object.toStringp();

        }
        jt_eliminar.setText(listar);

    }//GEN-LAST:event_jTabbedPane1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Agregardesk;
    private javax.swing.JButton JB_CRUD;
    private javax.swing.JButton JB_Simular;
    private javax.swing.JFrame JF_CRUD;
    private javax.swing.JFrame JF_Desk;
    private javax.swing.JFrame JF_Lap;
    private javax.swing.JButton JbEliminar;
    private javax.swing.ButtonGroup bg_Grafica;
    private javax.swing.ButtonGroup bg_rgb;
    private javax.swing.ButtonGroup bg_tipopc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbListar;
    private javax.swing.JButton jb_Agregarlap;
    private javax.swing.JButton jb_siguiente;
    private javax.swing.JRadioButton jr_desk;
    private javax.swing.JRadioButton jr_lap;
    private javax.swing.JRadioButton jrd_no;
    private javax.swing.JRadioButton jrd_si;
    private javax.swing.JRadioButton jrl_no;
    private javax.swing.JRadioButton jrl_si;
    private javax.swing.JTextField jt_alma;
    private javax.swing.JTextArea jt_eliminar;
    private javax.swing.JTextField jt_host;
    private javax.swing.JTextField jt_ip;
    private javax.swing.JTextArea jt_listar;
    private javax.swing.JTextField jt_marca;
    private javax.swing.JTextField jt_mask;
    private javax.swing.JTextField jt_pantalla;
    private javax.swing.JTextField jt_ram;
    private javax.swing.JTextField jt_tipohard;
    private javax.swing.JTextField jtelim;
    // End of variables declaration//GEN-END:variables
}
